library1/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace library1.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

library1/Controllers/autentificationController.cs
using Microsoft.AspNetCore.Mvc;

namespace library1
{
    public class AutentificationController : Controller
    {
        public IActionResult login()
        {
            return View();
        }
        public IActionResult createAccount()
        {
            return View();
        }
    }
}

library1/Views/Autentification/createAccount.cshtml
@using library1.Areas.Identity.Pages.Account
@{
 Layout=null;
}
@model RegisterModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/createAccount.css">
    <title>Create Account</title>
</head>
<body>
  
    <div class="createacc creatacc1">
         
             <!-- back to home, click the img in the corner top right in this div to return to the home page-->
              
             <a asp-controller="Home" asp-action="Index"><img src="../imageshtml/catt.png" alt="" id="cat"  width="50px" height="50px"></a>

              <!-- create account title -->

              <div class="cr">
                <h1 >Create your account</h1>
                <h3 id="start">Start browsing</h3>
              </div>
             
            <div class="register">
                <form id="registerForm" asp-route-returnUrl="@Model.ReturnUrl" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                  <!-- labels for first and last name -->
                @* <label class="reglabel" for="firstname">First Name:</label>
                 <label class="reglabel last" for="lastname">Last Name:</label><br>*@

                  <!-- inputs for first and last name -->
                 @*<input type="text" name="" id="first">
                 <input type="text" name="" id="first"><br>*@

                  <!-- label and input for email -->
                 <label class="reglabel" asp-for="Input.Email" >Email:</label><br>
                 <input asp-for="Input.Email" name="" id="email"><br>
                  <span asp-validation-for="Input.Email" class="text-danger"></span>

                  <!-- label and input for username -->
                  @* <label class="reglabel" asp-for="Input.UserName">Username:</label><br>
                  <input type="text" name="" asp-for="Input.UserName"><br> *@
            
                  <!-- label for password and confirm pass -->
                 <label class="reglabel"  asp-for="Input.Password">Password:</label>
                 <label class="reglabel pass" asp-for="Input.ConfirmPassword">Confirm password:</label><br>
                  
                 <!-- inputs for password and confirm pass -->
                 <input asp-for="Input.Password" name="" id="pass"><span asp-validation-for="Input.Password" class="text-danger"></span>
                 <input asp-for="Input.ConfirmPassword" name="" id="pass"><span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span><br>
                 


                 <!-- button to create account -->
                 <button class="button createnew" id="registerSubmit" type="submit"> <span> Create account</span></button>
                  <h4 id="log">Do you have an account? <a  asp-controller="Autentification" asp-action="login">Log in.</a></h4>  <!-- <-- go to log in page -->
              </form>
            </div>
           

    </div>

    
</body>
</html>

library1/Views/Autentification/login.cshtml
@{
 Layout=null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/login.css">
    <title>LogIn Page</title>
</head>

<body>
   
<!-- 1 big div who has 2 divs 1 for the login stage and one for going to the create an account page  -->

    <div class="login">

        <!-- div for the login stage -->
        <div class="loginclass">

             <div class="obiectelogin">
                <p class="signp">  Sign In</p>

                 <!-- label and input for username -->
                 <label for="Username" class="form-label">Username:</label> 
                 <input type="text" class="form-text" name="username" id="password">

                 <!-- label and input for pass of the user -->
                 <label for="Password" class="form-label">Password :</label> 
                 <input type="password"  class="form-text" name="password" id="password"><br><br>

                    <!-- button to sign in to the site -->
                 <button class="button signinbtn"><span>Sign In</span></button> 
            </div>
        </div>
      
        <!-- div for information if you dont own an account to lead you to the page where you can create one -->
        <div class="signupclass">

            <div class="imagine">

                <!-- click the image in the corner top right to go to the main page  -->
                <a asp-controller="Home" asp-action="Index"> <img src="../imageshtml/catt.png" class="backhome" width="50px"height="50px"></a>

            </div>

            <div class="obiectesignup">

                <h1 id="new">Are you new?</h1>
                <h3 id="create">Create an account and discover a lot of books</h3>

                 <!-- Press this button to go to the page where you can create an account if you re not registred yet -->
                <a asp-controller="Autentification" asp-action="createAccount"><button class="button createbtn"><span>Create account</span></button></a>
                
            </div>
        </div>
        
    </div>
    
</body>
</html>